##########################################################################################
# polymath/__init__.pyi
##########################################################################################
"""Type stub for the PolyMath package.

The `src` tree carries no inline annotations, so type information for the public symbols
is published here instead. Every public class is described in this one file, because the
only supported imports are ``from polymath import ...`` and
``from polymath.typedefs import ...``; the submodules that define the classes are an
implementation detail and carry no stubs of their own. The stub describes the shape of
the API exactly: every public name, its parameters, which of them are keyword-only, and
which have defaults. Types are taken from the docstrings wherever those state one
unambiguously, and are left as `Any` where they do not, rather than guessed at.

Class constants such as `Scalar.ZERO` are declared as attributes of their class. The
methods of `Qube` are bound onto the class from the extension modules when the package
is imported, and every one of them appears here as though it were defined in the class
body.
"""

import builtins
from collections.abc import Iterator, Mapping, Sequence
from typing import Any, ClassVar, NoReturn, TypeAlias

import numpy as np
from numpy.typing import NDArray

from polymath.typedefs import (BooleanLike, MaskType, Matrix3Like, PairLike, QubeLike,
                               ScalarLike, ValsType, Vector3Like, VectorLike)

__version__: str

__all__ = ['Boolean', 'Matrix', 'Matrix3', 'Pair', 'Polynomial', 'Quaternion', 'Qube',
           'Scalar', 'Unit', 'Vector', 'Vector3']

# Anything the constructors accept in place of a value: a PolyMath object, a NumPy array,
# a nested sequence, or a single number.
_Arraylike: TypeAlias = (Qube | NDArray[Any] | np.ma.MaskedArray[Any, Any] |
                         list[Any] | tuple[Any, ...] | float | builtins.int | bool)

# A bare "tuple" in a docstring, which is usually but not always a shape
_ShapeOrTuple: TypeAlias = tuple[Any, ...]

class Unit:
    ARCHOUR: Unit
    ARCHOURS: Unit
    ARCMIN: Unit
    ARCMINUTE: Unit
    ARCMINUTES: Unit
    ARCSEC: Unit
    ARCSECOND: Unit
    ARCSECONDS: Unit
    CENTIMETER: Unit
    CENTIMETERS: Unit
    CM: Unit
    CYCLE: Unit
    CYCLES: Unit
    D: Unit
    DAY: Unit
    DAYS: Unit
    DEG: Unit
    DEGREE: Unit
    DEGREES: Unit
    H: Unit
    HOUR: Unit
    HOURS: Unit
    KILOMETER: Unit
    KILOMETERS: Unit
    KM: Unit
    M: Unit
    METER: Unit
    METERS: Unit
    MICRON: Unit
    MICRONS: Unit
    MILLIMETER: Unit
    MILLIMETERS: Unit
    MILLIRAD: Unit
    MIN: Unit
    MINUTE: Unit
    MINUTES: Unit
    MM: Unit
    MRAD: Unit
    MS: Unit
    MSEC: Unit
    RAD: Unit
    RADIAN: Unit
    RADIANS: Unit
    REV: Unit
    REVS: Unit
    ROTATION: Unit
    ROTATIONS: Unit
    S: Unit
    SEC: Unit
    SECOND: Unit
    SECONDS: Unit
    STER: Unit
    UNITLESS: Unit
    def __copy__(self) -> Unit: ...
    def __div__(self, arg: Unit | float | int) -> Unit: ...
    def __eq__(self, arg: object) -> bool: ...
    def __init__(self, exponents: tuple[int, int, int], triple: tuple[int, int, int],
        name: str | dict | None = ...) -> None: ...  # type: ignore[type-arg]
    def __mul__(self, arg: Unit | float | int) -> Unit: ...
    def __ne__(self, arg: object) -> bool: ...
    def __pow__(self, power: int | float) -> Unit: ...
    def __rdiv__(self, arg: float | int | None) -> Unit: ...
    def __repr__(self) -> str: ...
    def __rmul__(self, arg: Unit | float | int) -> Unit: ...
    def __rtruediv__(self, arg: float | int | None) -> Unit: ...
    def __str__(self) -> str: ...
    def __truediv__(self, arg: Unit | float | int) -> Unit: ...
    @staticmethod
    def as_unit(arg: Unit | str | None) -> Unit | None: ...
    @staticmethod
    def can_match(first: Unit | None, second: Unit | None) -> bool: ...
    def convert(self, value: Any, unit: Unit | None, info: str = ...) -> Any: ...
    def copy(self) -> Unit: ...
    def create_name(self) -> str | dict: ...  # type: ignore[type-arg]
    @staticmethod
    def div_units(arg1: Unit | None, arg2: Unit | None) -> Unit | None: ...
    @staticmethod
    def do_match(first: Unit | None, second: Unit | None) -> bool: ...
    def from_this(self, value: Any) -> Any: ...
    @staticmethod
    def from_unit(unit: Unit | None, value: Any) -> Any: ...
    @property
    def from_unit_factor(self) -> float | int: ...
    def get_name(self) -> str | dict | None: ...  # type: ignore[type-arg]
    def into_this(self, value: Any) -> Any: ...
    @staticmethod
    def into_unit(unit: Unit | None, value) -> float | int | np.ndarray: ...  # type: ignore[no-untyped-def]
    @property
    def into_unit_factor(self) -> float | int: ...
    @staticmethod
    def is_angle(arg: Unit | None) -> bool: ...
    @staticmethod
    def is_unitless(arg: Unit | None) -> bool: ...
    @staticmethod
    def mul_units(arg1: Unit | None, arg2: Unit | None) -> Unit | None: ...
    @staticmethod
    def name_to_dict(expr: str | dict) -> dict: ...  # type: ignore[type-arg]
    @staticmethod
    def name_to_str(namedict: str | dict | None) -> str: ...  # type: ignore[type-arg]
    @staticmethod
    def require_angle(arg: Unit | None, info: str = ...) -> None: ...
    @staticmethod
    def require_compatible(first: Unit | None, second: Unit | None, info: str = ...
        ) -> None: ...
    @staticmethod
    def require_match(first: Unit | None, second: Unit | None, info: str = ...
        ) -> None: ...
    @staticmethod
    def require_unitless(arg: Unit | None, info: str = ...) -> None: ...
    def set_name(self, name: str | dict) -> Unit: ...  # type: ignore[type-arg]
    def sqrt(self) -> Unit: ...
    @staticmethod
    def sqrt_unit(unit: Unit | None) -> Unit | None: ...
    @staticmethod
    def unit_power(unit: Unit | None, power: int | float) -> Unit | None: ...

class Qube:
    # Lets NumPy defer to these operators rather than its own
    __array_priority__: ClassVar[builtins.int]

    # Qube compares by value and is mutable, so it is not hashable
    __hash__: ClassVar[None]  # type: ignore[assignment]
    def __abs__(self, *, recursive: bool = ...) -> Qube: ...
    def __add__(self, arg: QubeLike, *, recursive: bool = ...) -> Qube: ...
    def __and__(self, arg: BooleanLike) -> Boolean: ...
    def __bool__(self) -> Boolean: ...
    def __copy__(self) -> Qube: ...
    def __eq__(self, arg: object) -> Boolean: ...  # type: ignore[override]
    def __float__(self) -> float: ...
    def __floordiv__(self, arg: QubeLike) -> Qube: ...
    def __ge__(self, arg: QubeLike) -> Boolean: ...
    def __getitem__(self, indx: Any) -> Qube: ...
    def __getstate__(self) -> dict: ...  # type: ignore[type-arg]
    def __gt__(self, arg: QubeLike) -> Boolean: ...
    def __iadd__(self, arg: QubeLike) -> Qube: ...  # type: ignore[misc]
    def __iand__(self, arg: BooleanLike) -> Qube: ...
    def __ifloordiv__(self, arg: QubeLike) -> Qube: ...
    def __imod__(self, arg: QubeLike) -> Qube: ...  # type: ignore[misc]
    def __imul__(self, arg: QubeLike) -> Qube: ...  # type: ignore[misc]
    def __init__(self, arg: QubeLike, mask: BooleanLike = ..., *,
        derivs: Mapping[str, Qube] = ..., unit: Unit | None = ...,
        nrank: int | None = ..., drank: int | None = ..., example: Qube | None = ...,
        default: QubeLike | None = ..., op: str = ...) -> None: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> Boolean: ...
    def __ior__(self, arg: BooleanLike) -> Qube: ...
    def __ipow__(self, arg: QubeLike) -> Qube: ...
    def __isub__(self, arg: QubeLike) -> Qube: ...  # type: ignore[misc]
    def __iter__(self) -> Iterator[Qube]: ...
    def __itruediv__(self, arg: QubeLike) -> Qube: ...  # type: ignore[misc]
    def __ixor__(self, arg: BooleanLike) -> Qube: ...
    def __le__(self, arg: QubeLike) -> Boolean: ...
    def __len__(self) -> int: ...
    def __lt__(self, arg: QubeLike) -> Boolean: ...
    def __matmul__(self, arg: Qube) -> Qube: ...
    def __mod__(self, arg: QubeLike, *, recursive: bool = ...) -> Qube: ...
    def __mul__(self, arg: QubeLike, *, recursive: bool = ...) -> Qube: ...
    def __ne__(self, arg: object) -> Boolean: ...  # type: ignore[override]
    def __neg__(self, *, recursive: bool = ...) -> Qube: ...
    @staticmethod
    def __new__(subtype: type, *values: Any, **keywords: Any) -> Qube: ...
    def __or__(self, arg: BooleanLike) -> Boolean: ...
    def __pos__(self, *, recursive: bool = ...) -> Qube: ...
    def __pow__(self, arg: QubeLike) -> Qube: ...
    def __radd__(self, arg: QubeLike, *, recursive: bool = ...) -> Qube: ...
    def __rand__(self, arg: BooleanLike) -> Boolean: ...
    def __repr__(self) -> str: ...
    def __rfloordiv__(self, arg: QubeLike) -> Qube: ...
    def __rmod__(self, arg: QubeLike, *, recursive: bool = ...) -> Qube: ...
    def __rmul__(self, arg: QubeLike, *, recursive: bool = ...) -> Qube: ...
    def __ror__(self, arg: BooleanLike) -> Boolean: ...
    def __rsub__(self, arg: QubeLike, *, recursive: bool = ...) -> Qube: ...
    def __rtruediv__(self, arg: QubeLike, *, recursive: bool = ...) -> Qube: ...
    def __rxor__(self, arg: BooleanLike) -> Boolean: ...
    def __setitem__(self, indx: Any, arg: QubeLike) -> None: ...
    def __setstate__(self, state: dict[str, Any]) -> None: ...
    def __str__(self) -> str: ...
    def __sub__(self, arg: QubeLike, *, recursive: bool = ...) -> Qube: ...
    def __truediv__(self, arg: QubeLike, *, recursive: bool = ...) -> Qube: ...
    def __xor__(self, arg: BooleanLike) -> Boolean: ...
    def abs(self) -> Qube: ...
    def add_attr(self, name: str, value: Any | None = ...) -> Qube: ...
    def all(self, axis: int | Sequence[int] | None = ..., *,
        builtins: bool | None = ..., masked: bool | None = ..., out: Any | None = ...
        ) -> Boolean | bool: ...
    def all_true_or_masked(self, axis: int | Sequence[int] | None = ..., *,
        builtins: bool | None = ...) -> Boolean | bool: ...
    @staticmethod
    def and_(*masks: BooleanLike) -> np.ndarray | bool: ...
    @property
    def antimask(self) -> MaskType: ...
    def any(self, axis: int | Sequence[int] | None = ..., *,
        builtins: bool | None = ..., masked: bool | None = ..., out: Any | None = ...
        ) -> Boolean | bool: ...
    def any_true_or_masked(self, axis: int | Sequence[int] | None = ..., *,
        builtins: bool | None = ...) -> Boolean | bool: ...
    def as_all_constant(self, constant: QubeLike | None = ..., *, recursive: bool = ...
        ) -> Qube: ...
    def as_all_masked(self, *, recursive: bool = ...) -> Qube: ...
    def as_bool(self, *, copy: bool = ..., builtins: bool = ...) -> Qube: ...
    def as_builtin(self, masked: float | int | bool | None = ...
        ) -> Qube | float | int | bool | None: ...
    @staticmethod
    def as_diagonal(arg: Qube, axis: int,
        classes: type | list[type] | tuple[type, ...] = ..., recursive: bool = ...
        ) -> Qube: ...
    def as_float(self, *, recursive: bool = ..., copy: bool = ..., builtins: bool = ...
        ) -> Qube: ...
    def as_int(self, *, copy: bool = ..., builtins: bool = ...) -> Qube | int: ...
    def as_mask_where_nonzero(self) -> np.ndarray | bool: ...
    def as_mask_where_nonzero_or_masked(self) -> np.ndarray | bool: ...
    def as_mask_where_zero(self) -> np.ndarray | bool: ...
    def as_mask_where_zero_or_masked(self) -> np.ndarray | bool: ...
    def as_numeric(self, *, recursive: bool = ...) -> Qube: ...
    @staticmethod
    def as_one_bool(value: Any) -> Any: ...
    def as_one_masked(self, *, recursive: bool = ...) -> Qube: ...
    def as_readonly(self, *, recursive: bool = ...) -> Qube: ...
    def as_size_zero(self, axis: int = ..., *, recursive: bool = ...) -> Qube: ...
    def as_this_type(self, arg: QubeLike, *, recursive: bool = ..., coerce: bool = ...,
        op: str = ...) -> Qube: ...
    def broadcast(*objects: QubeLike | None, recursive: bool = ...,
        _protected: bool = ...) -> tuple[Any, ...]: ...
    def broadcast_into_shape(self, shape: tuple[int, ...], *, recursive: bool = ...,
        _protected: bool = ...) -> Qube: ...
    def broadcast_to(self, shape: tuple[int, ...], *, recursive: bool = ...,
        _protected: bool = ...) -> Qube: ...
    def broadcasted_shape(*objects: QubeLike | None, item: list | tuple = ...  # type: ignore[type-arg]
        ) -> tuple[int, ...]: ...
    def cast(self, classes: type | list[type] | tuple[type, ...]) -> Qube: ...
    def chain(self, arg: Qube) -> Qube: ...
    def clip(self, lower: Any, upper: Any, *, remask: bool = ..., inclusive: bool = ...
        ) -> Qube: ...
    def clone(self, *, recursive: bool = ...,
        preserve: str | list[str] | tuple[str, ...] | set[str] = ...,
        retain_cache: bool = ...) -> Qube: ...
    def collapse_mask(self, *, recursive: bool = ...) -> Qube: ...
    def confirm_unit(self, unit: Unit | None) -> Qube: ...
    def copy(self, *, recursive: bool = ..., readonly: bool = ...) -> Qube: ...
    @property
    def corners(self) -> tuple[tuple[int, int], tuple[int, int]] | None: ...
    def count_masked(self) -> int: ...
    def count_unmasked(self) -> int: ...
    @staticmethod
    def cross(arg1: Qube, arg2: Qube, axis1: int = ..., axis2: int = ..., *,
        classes: type | list[type] | tuple[type, ...] = ..., recursive: bool = ...
        ) -> Qube: ...
    @property
    def default(self) -> np.ndarray | float | int | bool: ...
    def delete_deriv(self, key: str, *, override: bool = ...) -> None: ...
    def delete_derivs(self, *, override: bool = ...,
        preserve: str | list[str] | tuple[str, ...] | set[str] | None = ...) -> None: ...
    @property
    def denom(self) -> tuple[int, ...]: ...
    @property
    def derivs(self) -> dict[str, Qube]: ...
    @staticmethod
    def dot(arg1: Qube, arg2: Qube, axis1: int = ..., axis2: int = ..., *,
        classes: type | list[type] | tuple[type, ...] = ..., recursive: bool = ...
        ) -> Qube: ...
    @property
    def drank(self) -> int: ...
    @property
    def dsize(self) -> int: ...
    def dtype(self) -> str: ...
    def expand_mask(self, *, recursive: bool = ...) -> Qube: ...
    def extract_denom(self, axis: int, index: int,
        classes: type | list[type] | tuple[type, ...] = ...) -> Qube: ...
    def extract_denoms(self) -> list: ...  # type: ignore[type-arg]
    def extract_numer(self, axis: int, index: int,
        classes: type | list[type] | tuple[type, ...] = ..., *, recursive: bool = ...
        ) -> Qube: ...
    @classmethod
    def filled(cls, shape: tuple[int, ...], fill: QubeLike = ..., *,
        numer: tuple[int, ...] | None = ..., denom: tuple[int, ...] = ...,
        mask: BooleanLike = ...) -> Qube: ...
    def flatten(self, *, recursive: bool = ...) -> Qube: ...
    def flatten_denom(self) -> Qube: ...
    def flatten_numer(self, classes: type | list[type] | tuple[type, ...] = ..., *,
        recursive: bool = ...) -> Qube: ...
    @classmethod
    def from_scalars(cls, *scalars: QubeLike, recursive: bool = ...,
        readonly: bool = ..., classes: type | list[type] | tuple[type, ...] = ...
        ) -> Qube: ...
    def identity(self) -> None: ...
    def insert_deriv(self, key: str, deriv: Qube, *, override: bool = ...) -> Qube: ...
    def insert_derivs(self, derivs: Mapping[str, Qube], *,
        override: bool = ...) -> Qube: ...
    def into_unit(self, *, recursive: bool = ...
        ) -> np.ndarray | float | int | bool | tuple: ...  # type: ignore[type-arg]
    @staticmethod
    def is_above(arg: Any, high: Any, *, inclusive: bool = ...) -> bool: ...
    def is_all_masked(self) -> bool: ...
    @staticmethod
    def is_below(arg: Any, high: Any, *, inclusive: bool = ...) -> bool: ...
    def is_bool(self) -> bool: ...
    def is_float(self) -> bool: ...
    @staticmethod
    def is_inside(arg: Any, low: Any, high: Any, *, inclusive: bool = ...) -> bool: ...
    def is_int(self) -> bool: ...
    def is_numeric(self) -> bool: ...
    @staticmethod
    def is_one_false(value: Any) -> bool: ...
    @staticmethod
    def is_one_true(value: Any) -> bool: ...
    @staticmethod
    def is_outside(arg: Any, low: Any, high: Any, *, inclusive: bool = ...) -> bool: ...
    def is_unitless(self) -> bool: ...
    @property
    def isize(self) -> int: ...
    @property
    def item(self) -> tuple[int, ...]: ...
    def join_items(self, classes: type | list[type] | tuple[type, ...]) -> Qube: ...
    def len(self) -> int: ...
    def logical_not(self) -> Boolean: ...
    @property
    def mask(self) -> MaskType: ...
    def mask_where(self, mask: BooleanLike, replace: Any | None = ..., *,
        remask: bool = ..., recursive: bool = ...) -> Qube: ...
    def mask_where_between(self, lower: QubeLike, upper: QubeLike, *,
        mask_endpoints: bool | Sequence[bool] = ..., replace: QubeLike | None = ...,
        remask: bool = ...) -> Qube: ...
    def mask_where_eq(self, match: Any, replace: Any | None = ..., *, remask: bool = ...
        ) -> Qube: ...
    def mask_where_ge(self, limit: Any, replace: Any | None = ..., *, remask: bool = ...
        ) -> Qube: ...
    def mask_where_gt(self, limit: Any, replace: Any | None = ..., *, remask: bool = ...
        ) -> Qube: ...
    def mask_where_le(self, limit: Any, replace: Any | None = ..., *, remask: bool = ...
        ) -> Qube: ...
    def mask_where_lt(self, limit: Any, replace: Any | None = ..., *, remask: bool = ...
        ) -> Qube: ...
    def mask_where_ne(self, match: Any, replace: Any | None = ..., *, remask: bool = ...
        ) -> Qube: ...
    def mask_where_outside(self, lower: QubeLike, upper: QubeLike, *,
        mask_endpoints: bool | Sequence[bool] = ..., replace: QubeLike | None = ...,
        remask: bool = ...) -> Qube: ...
    def masked_single(self, *, recursive: bool = ...) -> Qube: ...
    def match_readonly(self, arg: Qube) -> Qube: ...
    def mean(self, axis: int | Sequence[int] | None = ..., *, recursive: bool = ...,
        builtins: bool | None = ..., masked: bool | None = ..., dtype: Any | None = ...,
        out: Any | None = ...) -> Qube | float | int: ...
    def move_axis(self, source: int | tuple[int, ...],
        destination: int | tuple[int, ...], *, recursive: bool = ...,
        rank: int | None = ...) -> Qube: ...
    @property
    def mvals(self) -> np.ma.MaskedArray: ...
    def ndenumerate(self) -> Iterator[tuple[tuple[int, ...], Qube]]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def ndims(self) -> int: ...
    @staticmethod
    def norm(arg: Qube, axis: int = ..., *,
        classes: type | list[type] | tuple[type, ...] = ..., recursive: bool = ...
        ) -> Qube: ...
    @staticmethod
    def norm_sq(arg: QubeLike, axis: int = ..., *,
        classes: type | list[type] | tuple[type, ...] = ..., recursive: bool = ...
        ) -> Qube: ...
    @property
    def nrank(self) -> int: ...
    @property
    def nsize(self) -> int: ...
    @property
    def numer(self) -> tuple[int, ...]: ...
    @classmethod
    def ones(cls, shape: tuple[int, ...], dtype: str = ..., *,
        numer: tuple[int, ...] | None = ..., denom: tuple[int, ...] = ...,
        mask: BooleanLike = ...) -> Qube: ...
    @staticmethod
    def or_(*masks: BooleanLike) -> np.ndarray | bool: ...
    @staticmethod
    def outer(arg1: Qube, arg2: Qube,
        classes: type | list[type] | tuple[type, ...] = ..., recursive: bool = ...
        ) -> Qube: ...
    def pickle_digits(self) -> tuple[str | float | int,
                                    str | float | int]: ...
    def pickle_reference(self) -> tuple[str | float | int,
                                    str | float | int]: ...
    @staticmethod
    def prefer_builtins(status: bool | None = ...) -> bool: ...
    @property
    def rank(self) -> int: ...
    @property
    def readonly(self) -> bool: ...
    def reciprocal(self, *, recursive: bool = ..., nozeros: bool = ...) -> None: ...
    def remask(self, mask: BooleanLike, *, recursive: bool = ..., check: bool = ...
        ) -> Qube: ...
    def remask_or(self, mask: BooleanLike, *, recursive: bool = ..., check: bool = ...
        ) -> Qube: ...
    def rename_deriv(self, key: str, new_key: str, *, method: str = ...) -> Qube: ...
    def require_writable(self, force: bool = ...) -> Qube: ...
    def require_writeable(self, force: bool = ...) -> Qube: ...
    def reshape(self, shape: tuple[int, ...] | int, *, recursive: bool = ...) -> Qube: ...
    def reshape_denom(self, shape: tuple[int, ...]) -> Qube: ...
    def reshape_numer(self, shape: tuple[int, ...],
        classes: type | list[type] | tuple[type, ...] = ..., recursive: bool = ...
        ) -> Qube: ...
    def rms(self) -> Scalar: ...
    def roll_axis(self, axis: int, start: int = ..., *, recursive: bool = ...,
        rank: int | None = ...) -> Qube: ...
    @staticmethod
    def set_default_pickle_digits(digits: int | float | str | tuple = ...,  # type: ignore[type-arg]
        reference: int | float | str | tuple = ...) -> None: ...  # type: ignore[type-arg]
    def set_pickle_digits(self, digits: int | float | str | Sequence[Any] | None = ...,
        reference: int | float | str | Sequence[Any] | None = ...) -> None: ...
    def set_unit(self, unit: Unit | None, *, override: bool = ...) -> None: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    def shrink(self, antimask: BooleanLike) -> Qube: ...
    @property
    def size(self) -> int: ...
    def slice_numer(self, axis: int, index1: int, index2: int,
        classes: type | list[type] | tuple[type, ...] = ..., *, recursive: bool = ...
        ) -> Qube: ...
    def split_items(self, nrank: int, classes: type | list[type] | tuple[type, ...]
        ) -> Qube: ...
    @staticmethod
    def stack(*args: ScalarLike | None, recursive: bool = ...) -> Qube: ...
    def sum(self, axis: int | Sequence[int] | None = ..., *, recursive: bool = ...,
        builtins: bool | None = ..., masked: bool | None = ..., out: Any | None = ...
        ) -> Qube | float | int: ...
    def swap_axes(self, axis1: int, axis2: int, *, recursive: bool = ...) -> Qube: ...
    def swap_items(self, classes: type | list[type] | tuple[type, ...]) -> Qube: ...
    def transpose_denom(self, axis1: int = ..., axis2: int = ...) -> Qube: ...
    def transpose_numer(self, axis1: int = ..., axis2: int = ..., *,
        recursive: bool = ...) -> Qube: ...
    def tvl_all(self, axis: int | Sequence[int] | None = ...,
        builtins: bool | None = ..., masked: bool | None = ...) -> Boolean | bool: ...
    def tvl_and(self, arg: BooleanLike, builtins: bool | None = ...,
        masked: bool | None = ...) -> Boolean | bool: ...
    def tvl_any(self, axis: int | Sequence[int] | None = ...,
        builtins: bool | None = ..., masked: bool | None = ...) -> Boolean | bool: ...
    def tvl_eq(self, arg: BooleanLike, builtins: bool | None = ...) -> Boolean | bool: ...
    def tvl_ge(self, arg: QubeLike, builtins: bool | None = ...) -> Boolean | bool: ...
    def tvl_gt(self, arg: QubeLike, builtins: bool | None = ...) -> Boolean | bool: ...
    def tvl_le(self, arg: QubeLike, builtins: bool | None = ...) -> Boolean | bool: ...
    def tvl_lt(self, arg: QubeLike, builtins: bool | None = ...) -> Boolean | bool: ...
    def tvl_ne(self, arg: BooleanLike, builtins: bool | None = ...) -> Boolean | bool: ...
    def tvl_or(self, arg: BooleanLike, builtins: bool | None = ...,
        masked: bool | None = ...) -> Boolean | bool: ...
    def unique_deriv_name(self, key: str, *objects: Qube) -> str: ...
    @property
    def unit_(self) -> Unit | None: ...
    @property
    def units(self) -> Unit | None: ...
    def unshrink(self, antimask: BooleanLike, shape: tuple[int, ...] = ...) -> Qube: ...
    @property
    def vals(self) -> ValsType: ...
    @property
    def values(self) -> ValsType: ...
    def with_deriv(self, key: str, value: Qube, *, method: str = ...) -> Qube: ...
    def without_deriv(self, key: str) -> Qube: ...
    def without_derivs(self, *,
        preserve: str | list[str] | tuple[str, ...] | set[str] | None = ...) -> Qube: ...
    def without_mask(self, *, recursive: bool = ...) -> Qube: ...
    def without_unit(self, *, recursive: bool = ...) -> Qube: ...
    @property
    def wod(self) -> Qube: ...
    def zero(self) -> Qube: ...
    @classmethod
    def zeros(cls, shape: tuple[int, ...], dtype: str = ..., *,
        numer: tuple[int, ...] | None = ..., denom: tuple[int, ...] = ...,
        mask: BooleanLike = ...) -> Qube: ...

class Scalar(Qube):
    HALFPI: Scalar
    INF: Scalar
    MASKED: Scalar
    NEGINF: Scalar
    ONE: Scalar
    PI: Scalar
    THREE: Scalar
    TWO: Scalar
    TWOPI: Scalar
    ZERO: Scalar
    def __abs__(self, *, recursive: bool = ...) -> Scalar: ...  # type: ignore[override]
    def __ge__(self, arg: Any, *, builtins: bool = ...  # type: ignore[override]
        ) -> Boolean | bool: ...
    def __gt__(self, arg: Any, *, builtins: bool = ...  # type: ignore[override]
        ) -> Boolean | bool: ...
    def __le__(self, arg: Any, *, builtins: bool = ...  # type: ignore[override]
        ) -> Boolean | bool: ...
    def __lt__(self, arg: Any, *, builtins: bool = ...  # type: ignore[override]
        ) -> Boolean | bool: ...
    def __pow__(self, expo: ScalarLike, *, recursive: bool = ...) -> Scalar: ...
    def __round__(self, digits: builtins.int) -> Scalar: ...
    def abs(self, *, recursive: bool = ...) -> Scalar: ...
    def arccos(self, *, recursive: bool = ..., check: bool = ...) -> Scalar: ...
    def arcsin(self, *, recursive: bool = ..., check: bool = ...) -> Scalar: ...
    def arctan(self, *, recursive: bool = ...) -> Scalar: ...
    def arctan2(self, arg: ScalarLike, *, recursive: bool = ...) -> Scalar: ...
    def argmax(self, axis: builtins.int | tuple[builtins.int, ...] | None = ..., *,
        builtins: bool | None = ...,
        masked: builtins.int | None = ...) -> Scalar | builtins.int: ...
    def argmin(self, axis: builtins.int | tuple[builtins.int, ...] | None = ..., *,
        builtins: bool | None = ...,
        masked: builtins.int | None = ...) -> Scalar | builtins.int: ...
    def as_index(self, *, masked: builtins.int | None = ...
        ) -> np.ndarray | builtins.int: ...
    def as_index_and_mask(self, *, purge: bool = ..., masked: builtins.int | None = ...
        ) -> tuple[np.ndarray | builtins.int, np.ndarray | builtins.bool]: ...
    @staticmethod
    def as_scalar(arg: Any, *, recursive: bool = ...) -> Scalar: ...
    def cos(self, *, recursive: bool = ...) -> Scalar: ...
    def eval_quadratic(self, a: ScalarLike, b: ScalarLike, c: ScalarLike, *,
        recursive: bool = ...) -> Scalar: ...
    def exp(self, *, recursive: bool = ..., check: bool = ...) -> Scalar: ...
    def frac(self, *, recursive: bool = ...) -> Scalar: ...
    def identity(self) -> Scalar: ...  # type: ignore[override]
    def int(self, top: builtins.int | None = ..., *, remask: bool = ..., clip: bool = ...,
        inclusive: bool = ..., shift: bool | None = ..., builtins: bool | None = ...,
        masked: builtins.int | None = ...) -> Scalar | builtins.int: ...
    def log(self, *, recursive: bool = ..., check: bool = ...) -> Scalar: ...
    def max(self, axis: builtins.int | tuple[builtins.int, ...] | None = ..., *,
        builtins: bool | None = ..., masked: float | builtins.int | None = ...,
        out: Any | None = ...) -> Scalar | float | builtins.int: ...
    @staticmethod
    def maximum(*args: ScalarLike) -> Scalar: ...
    def median(self, axis: builtins.int | tuple[builtins.int, ...] | None = ..., *,
        builtins: bool | None = ..., masked: float | builtins.int | None = ...,
        out: Any | None = ...) -> Scalar | float | builtins.int: ...
    def min(self, axis: builtins.int | tuple[builtins.int, ...] | None = ..., *,
        builtins: bool | None = ..., masked: float | builtins.int | None = ...,
        out: Any | None = ...) -> Scalar | float | builtins.int: ...
    @staticmethod
    def minimum(*args: ScalarLike) -> Scalar: ...
    def reciprocal(self, *, recursive: bool = ..., nozeros: bool = ...  # type: ignore[override]
        ) -> Scalar: ...
    def sign(self, *, zeros: bool = ..., builtins: bool | None = ...,
        masked: builtins.int | None = ...) -> Scalar | builtins.int: ...
    def sin(self, *, recursive: bool = ...) -> Scalar: ...
    @staticmethod
    def solve_quadratic(a: ScalarLike, b: ScalarLike, c: ScalarLike, *,
        recursive: bool = ..., include_antimask: bool = ...
        ) -> tuple[Scalar, Scalar] | tuple[Scalar, Scalar, Boolean]: ...
    def sort(self, axis: builtins.int = ...) -> Scalar: ...
    def sqrt(self, *, recursive: bool = ..., check: bool = ...) -> Scalar: ...
    def tan(self, *, recursive: bool = ...) -> Scalar: ...
    def to_scalar(self, indx: builtins.int, *, recursive: bool = ...) -> Scalar: ...

class Boolean(Scalar):
    FALSE: Boolean
    MASKED: Boolean
    TRUE: Boolean
    def __abs__(self, *, recursive: bool = ...) -> Scalar: ...  # type: ignore[override]
    def __add__(self, arg: Any, *, recursive: bool = ...  # type: ignore[override]
        ) -> Scalar: ...
    def __floordiv__(self, arg: Any) -> Scalar: ...
    def __ge__(self, arg: Any, *, builtins: bool = ...  # type: ignore[override]
        ) -> Boolean | bool: ...
    def __gt__(self, arg: Any, *, builtins: bool = ...  # type: ignore[override]
        ) -> Boolean | bool: ...
    def __iadd__(self, arg: Any) -> None: ...  # type: ignore[misc, override]
    def __ifloordiv__(self, arg: Any) -> None: ...  # type: ignore[override]
    def __imod__(self, arg: Any) -> None: ...  # type: ignore[override]
    def __imul__(self, arg: Any) -> None: ...  # type: ignore[misc, override]
    def __ipow__(self, arg: Any) -> None: ...  # type: ignore[override]
    def __isub__(self, arg: Any) -> None: ...  # type: ignore[misc, override]
    def __itruediv__(self, arg: Any) -> None: ...  # type: ignore[misc, override]
    def __le__(self, arg: Any, *, builtins: bool = ...  # type: ignore[override]
        ) -> Boolean | bool: ...
    def __lt__(self, arg: Any, *, builtins: bool = ...  # type: ignore[override]
        ) -> Boolean | bool: ...
    def __mod__(self, arg: Any) -> Scalar: ...  # type: ignore[override]
    def __mul__(self, arg: Any, *, recursive: bool = ...  # type: ignore[override]
        ) -> Scalar: ...
    def __neg__(self, *, recursive: bool = ...) -> Scalar: ...  # type: ignore[override]
    def __pos__(self, *, recursive: bool = ...) -> Scalar: ...  # type: ignore[override]
    def __pow__(self, arg: Any) -> Scalar: ...  # type: ignore[override]
    def __radd__(self, arg: Any, *, recursive: bool = ...  # type: ignore[override]
        ) -> Scalar: ...
    def __rfloordiv__(self, arg: Any) -> Scalar: ...
    def __rmod__(self, arg: Any) -> Scalar: ...  # type: ignore[override]
    def __rmul__(self, arg: Any, *, recursive: bool = ...  # type: ignore[override]
        ) -> Scalar: ...
    def __rsub__(self, arg: Any, *, recursive: bool = ...  # type: ignore[override]
        ) -> Scalar: ...
    def __rtruediv__(self, arg: Any, *, recursive: bool = ...  # type: ignore[override]
        ) -> Scalar: ...
    def __sub__(self, arg: Any, *, recursive: bool = ...  # type: ignore[override]
        ) -> Scalar: ...
    def __truediv__(self, arg: Any, *, recursive: bool = ...  # type: ignore[override]
        ) -> Scalar: ...
    @staticmethod
    def as_boolean(arg: Any, *, recursive: bool = ...) -> Boolean: ...
    def as_index(self) -> np.ndarray | bool: ...  # type: ignore[override]
    def identity(self) -> Boolean: ...  # type: ignore[override]
    def sum(self, axis: int | Sequence[int] | None = ..., *, value: bool = ...,
        builtins: bool | None = ..., recursive: bool = ..., masked: bool | None = ...,
        out: Any | None = ...) -> Scalar: ...

class Vector(Qube):
    MASKED2: Vector
    MASKED3: Vector
    XAXIS2: Vector
    XAXIS3: Vector
    YAXIS2: Vector
    YAXIS3: Vector
    ZAXIS3: Vector
    ZERO2: Vector
    ZERO3: Vector
    def __abs__(self, recursive: bool = ...) -> Scalar: ...  # type: ignore[override]
    def __init__(self, arg: VectorLike | float | int, *args: Any,
        **kwargs: Any) -> None: ...
    def as_column(self, recursive: bool = ...) -> Matrix: ...
    def as_diagonal(self, *, recursive: bool = ...  # type: ignore[override]
        ) -> Matrix: ...
    def as_index(self, *, masked: ScalarLike | None = ...
        ) -> tuple[np.ndarray, ...]: ...
    def as_index_and_mask(self, *, purge: bool = ..., masked: ScalarLike | None = ...
        ) -> tuple: ...  # type: ignore[type-arg]
    def as_row(self, *, recursive: bool = ...) -> Matrix: ...
    @staticmethod
    def as_vector(arg: Any, *, recursive: bool = ...) -> Vector: ...
    def clip_component(self, axis: builtins.int, lower: ScalarLike | None,
        upper: ScalarLike | None, remask: bool = ...) -> Vector: ...
    @classmethod
    def combos(cls, *args: ScalarLike) -> Vector: ...
    def cross(self, arg: VectorLike, *, recursive: bool = ...  # type: ignore[override]
        ) -> Vector | Scalar: ...
    def cross_product_as_matrix(self, *, recursive: bool = ...) -> Matrix: ...
    def dot(self, arg: VectorLike, *, recursive: bool = ...  # type: ignore[override]
        ) -> Scalar: ...
    def element_div(self, arg: VectorLike, recursive: bool = ...) -> Vector: ...
    def element_mul(self, arg: VectorLike, *, recursive: bool = ...) -> Vector: ...
    @staticmethod
    def from_scalars(*args: ScalarLike | None, recursive: bool = ...,  # type: ignore[override]
        readonly: bool = ...) -> Vector: ...
    def identity(self) -> None: ...
    def int(self, top: builtins.int | tuple[builtins.int, ...] | None = ..., *,
        remask: bool = ...,
        clip: bool | tuple[bool, ...] = ..., inclusive: bool | tuple[bool, ...] = ...,
        shift: bool | tuple[bool, ...] | None = ...) -> Vector: ...
    def mask_where_component_ge(self, axis: builtins.int, limit: ScalarLike,
        replace: ScalarLike | None = ..., remask: bool = ...) -> Vector: ...
    def mask_where_component_gt(self, axis: builtins.int, limit: ScalarLike,
        replace: ScalarLike | None = ..., remask: bool = ...) -> Vector: ...
    def mask_where_component_le(self, axis: builtins.int, limit: ScalarLike,
        replace: ScalarLike | None = ..., remask: bool = ...) -> Vector: ...
    def mask_where_component_lt(self, axis: builtins.int, limit: ScalarLike,
        replace: ScalarLike | None = ..., remask: bool = ...) -> Vector: ...
    def norm(self, *, recursive: bool = ...) -> Scalar: ...  # type: ignore[override]
    def norm_sq(self, *, recursive: bool = ...) -> Scalar: ...  # type: ignore[override]
    def outer(self, arg: VectorLike, *, recursive: bool = ...  # type: ignore[override]
        ) -> Matrix: ...
    def perp(self, arg: VectorLike, *, recursive: bool = ...) -> Vector: ...
    def proj(self, arg: VectorLike, *, recursive: bool = ...) -> Vector: ...
    def reciprocal(self, nozeros: bool = ...) -> Vector: ...  # type: ignore[override]
    def sep(self, arg: VectorLike, *, recursive: bool = ...) -> Scalar: ...
    def to_pair(self, axes: tuple[builtins.int, ...] = ..., *, recursive: bool = ...
        ) -> Pair: ...
    def to_scalar(self, indx: builtins.int, *, recursive: bool = ...) -> Scalar: ...
    def to_scalars(self, *, recursive: bool = ...) -> tuple: ...  # type: ignore[type-arg]
    def ucross(self, arg: VectorLike, *, recursive: bool = ...) -> Vector: ...
    def unit(self, *, recursive: bool = ...) -> Vector: ...
    def vector_scale(self, factor: Vector, recursive: bool = ...) -> Vector: ...
    def vector_unscale(self, factor: Vector, recursive: bool = ...) -> Vector: ...
    def with_norm(self, norm: ScalarLike = ..., *, recursive: bool = ...) -> Vector: ...

class Pair(Vector):
    HALF: Pair
    IDENTITY: Pair
    INT00: Pair
    INT11: Pair
    MASKED: Pair
    ONES: Pair
    XAXIS: Pair
    YAXIS: Pair
    ZERO: Pair
    ZEROS: Pair
    def angle(self, *, recursive: bool = ...) -> Scalar: ...
    @staticmethod
    def as_pair(arg: Any, *, recursive: bool = ...) -> Pair: ...
    def clip2d(self, lower: PairLike | None, upper: PairLike | None, *,
        remask: bool = ...) -> Pair: ...
    @staticmethod
    def from_scalars(x: ScalarLike | None, y: ScalarLike | None, *,  # type: ignore[override]
        recursive: bool = ..., readonly: bool = ...) -> Pair: ...
    def rot90(self, *, recursive: bool = ...) -> Pair: ...
    def swapxy(self, *, recursive: bool = ...) -> Pair: ...

class Vector3(Vector):
    AXES: tuple[Any, ...]
    IDENTITY: Vector3
    MASKED: Vector3
    ONES: Vector3
    XAXIS: Vector3
    YAXIS: Vector3
    ZAXIS: Vector3
    ZERO: Vector3
    ZERO_POS_VEL: Vector3
    @staticmethod
    def as_vector3(arg: Any, *, recursive: bool = ...) -> Vector3: ...
    @staticmethod
    def from_cylindrical(radius: ScalarLike, longitude: ScalarLike, z: ScalarLike = ...,
        *, recursive: bool = ...) -> Vector3: ...
    @staticmethod
    def from_ra_dec_length(ra: ScalarLike, dec: ScalarLike, length: ScalarLike = ..., *,
        recursive: bool = ...) -> Vector3: ...
    @staticmethod
    def from_scalars(x: ScalarLike | None, y: ScalarLike | None,  # type: ignore[override]
        z: ScalarLike | None, *, recursive: bool = ...,
        readonly: bool = ...) -> Vector3: ...
    def latitude(self, *, recursive: bool = ...) -> Scalar: ...
    def longitude(self, *, recursive: bool = ...) -> Scalar: ...
    def offset_angles(self, vector: Vector3Like, *, recursive: bool = ...
        ) -> tuple[Scalar, Scalar]: ...
    def spin(self, pole: Vector3Like, angle: ScalarLike | None = ..., *,
        recursive: bool = ...) -> Vector3: ...
    def to_cylindrical(self, *, recursive: bool = ...
        ) -> tuple[Scalar, Scalar, Scalar]: ...
    def to_ra_dec_length(self, *, recursive: bool = ...
        ) -> tuple[Scalar, Scalar, Scalar]: ...

class Quaternion(Vector):
    IDENTITY: Quaternion
    MASKED: Quaternion
    XAXIS: Quaternion
    YAXIS: Quaternion
    ZAXIS: Quaternion
    ZERO: Quaternion
    def __mul__(self, arg: Any, *, recursive: bool = ...  # type: ignore[override]
        ) -> Quaternion: ...
    def __rmul__(self, arg: Any, *, recursive: bool = ...  # type: ignore[override]
        ) -> Quaternion: ...
    def __truediv__(self, arg: Any, *, recursive: bool = ...  # type: ignore[override]
        ) -> Quaternion: ...
    @staticmethod
    def as_quaternion(arg: Any, *, recursive: bool = ...) -> Quaternion: ...
    def conj(self, *, recursive: bool = ...) -> Quaternion: ...
    @staticmethod
    def from_euler(ai: ScalarLike, aj: ScalarLike, ak: ScalarLike,
        axes: str | tuple[int, int, int, int] = ...) -> Quaternion: ...
    @staticmethod
    def from_euler_via_matrix(ai: ScalarLike, aj: ScalarLike, ak: ScalarLike,
        axes: str | tuple[int, int, int, int] = ...) -> Quaternion: ...
    @staticmethod
    def from_matrix3(matrix: Matrix3Like, *, recursive: bool = ...) -> Quaternion: ...
    @staticmethod
    def from_parts(scalar: ScalarLike | None, vector: Vector3Like | None, *,
        recursive: bool = ...) -> Quaternion: ...
    @staticmethod
    def from_rotation(angle: ScalarLike, vector: Vector3Like, *, recursive: bool = ...
        ) -> Quaternion: ...
    def identity(self) -> Quaternion: ...  # type: ignore[override]
    def reciprocal(self, *, recursive: bool = ...  # type: ignore[override]
        ) -> Quaternion: ...
    def to_euler(self, axes: str | tuple[int, int, int, int] = ...
        ) -> tuple[Scalar, Scalar, Scalar]: ...
    def to_matrix3(self, *, recursive: bool = ..., partials: bool = ...
        ) -> Matrix3 | tuple[Matrix3, Matrix]: ...
    def to_parts(self, *, recursive: bool = ...) -> tuple[Scalar, Vector3]: ...
    def to_rotation(self, *, recursive: bool = ...) -> tuple[Scalar | float, Vector3]: ...

class Polynomial(Vector):
    def __add__(self, arg: Any) -> Polynomial: ...  # type: ignore[override]
    def __eq__(self, arg: object) -> bool: ...  # type: ignore[override]
    def __iadd__(self, arg: Any) -> Polynomial: ...  # type: ignore[override]
    def __imul__(self, arg: Any) -> Polynomial: ...  # type: ignore[override]
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __isub__(self, arg: QubeLike) -> Polynomial: ...  # type: ignore[override, misc]
    def __itruediv__(self, arg: Any) -> Polynomial: ...  # type: ignore[override]
    def __mul__(self, arg: Any) -> Polynomial: ...  # type: ignore[override]
    def __ne__(self, arg: object) -> bool: ...  # type: ignore[override]
    def __neg__(self) -> Polynomial: ...  # type: ignore[override]
    def __pow__(self, arg: Any) -> Polynomial: ...
    def __radd__(self, arg: Any) -> Polynomial: ...  # type: ignore[override]
    def __rmul__(self, arg: Any) -> Polynomial: ...  # type: ignore[override]
    def __rsub__(self, arg: Any) -> Polynomial: ...  # type: ignore[override]
    def __sub__(self, arg: Any) -> Polynomial: ...  # type: ignore[override]
    def __truediv__(self, arg: Any) -> Polynomial: ...  # type: ignore[override]
    @staticmethod
    def as_polynomial(arg: Any, *, recursive: bool = ...) -> Polynomial: ...
    def as_vector(self, *, recursive: bool = ...) -> Vector: ...  # type: ignore[override]
    def at_least_order(self, order: int, *, recursive: bool = ...) -> Polynomial: ...
    def deriv(self, recursive: bool = ...) -> Polynomial: ...
    def eval(self, x: ScalarLike, recursive: bool = ...) -> Scalar: ...
    def invert_line(self, *, recursive: bool = ...) -> Polynomial: ...
    @property
    def order(self) -> int: ...
    def roots(self, recursive: bool = ...) -> Scalar: ...
    def set_order(self, order: int, *, recursive: bool = ...) -> Polynomial: ...

class Matrix(Qube):
    IDENTITY2: Matrix
    IDENTITY3: Matrix
    MASKED2: Matrix
    MASKED3: Matrix
    @property
    def T(self) -> Matrix: ...  # noqa: N802
    UNIT33: Matrix
    XAXIS_COL: Matrix
    XAXIS_ROW: Matrix
    YAXIS_COL: Matrix
    YAXIS_ROW: Matrix
    ZAXIS_COL: Matrix
    ZAXIS_ROW: Matrix
    ZERO33: Matrix
    ZERO3_COL: Matrix
    ZERO3_ROW: Matrix
    def __abs__(self) -> None: ...  # type: ignore[override]
    def __floordiv__(self, arg: Any) -> NoReturn: ...  # type: ignore[override]
    def __ifloordiv__(self, arg: Any) -> NoReturn: ...  # type: ignore[override]
    def __imod__(self, arg: Any) -> NoReturn: ...  # type: ignore[override]
    def __mod__(self, arg: Any) -> NoReturn: ...  # type: ignore[override]
    def __rfloordiv__(self, arg: Any) -> NoReturn: ...  # type: ignore[override]
    def __rmod__(self, arg: Any) -> NoReturn: ...  # type: ignore[override]
    @staticmethod
    def as_matrix(arg: Any, *, recursive: bool = ...) -> Matrix: ...
    def column_vector(self, column: int, *, recursive: bool = ...,
        classes: type | list[type] | tuple[type, ...] = ...) -> Qube: ...
    def column_vectors(self, recursive: bool = ...,
        classes: type | list[type] | tuple[type, ...] = ...) -> tuple[Qube, ...]: ...
    @staticmethod
    def from_scalars(*args: Any, recursive: bool = ...,  # type: ignore[override]
        shape: tuple[int, ...] | None = ...,
        classes: type | list[type] | tuple[type, ...] = ...) -> Matrix: ...
    def identity(self) -> Matrix: ...  # type: ignore[override]
    def inverse(self, *, recursive: bool = ..., nozeros: bool = ...) -> Matrix: ...
    def is_diagonal(self, *, delta: float = ...) -> Boolean: ...
    def reciprocal(self, *, recursive: bool = ..., nozeros: bool = ...  # type: ignore[override]
        ) -> Matrix: ...
    def row_vector(self, row: int, *, recursive: bool = ...,
        classes: type | list[type] | tuple[type, ...] = ...) -> Qube: ...
    def row_vectors(self, *, recursive: bool = ...,
        classes: type | list[type] | tuple[type, ...] = ...) -> tuple[Qube, ...]: ...
    def solve(self, arg: Vector | list | tuple, *, recursive: bool = ...,  # type: ignore[type-arg]
        nozeros: bool = ...) -> Vector: ...
    def to_scalar(self, indx0: int, indx1: int, *, recursive: bool = ...) -> Scalar: ...
    def to_vector(self, axis: int, indx: int, *, recursive: bool = ...,
        classes: type | list[type] | tuple[type, ...] = ...) -> Qube: ...
    def transpose(self, *, recursive: bool = ...) -> Matrix: ...
    def unitary(self) -> Matrix3: ...

class Matrix3(Matrix):
    IDENTITY: Matrix3
    MASKED: Matrix3
    def __add__(self, arg: Any) -> None: ...  # type: ignore[override]
    def __getstate__(self) -> dict: ...  # type: ignore[type-arg]
    def __iadd__(self, arg: Any) -> None: ...  # type: ignore[override]
    def __imul__(self, arg: Any) -> Matrix3: ...  # type: ignore[misc, override]
    def __isub__(self, arg: Any) -> None: ...  # type: ignore[override]
    def __mul__(self, arg: Any, *, recursive: bool = ...  # type: ignore[override]
        ) -> Qube: ...
    def __neg__(self) -> None: ...  # type: ignore[override]
    def __radd__(self, arg: Any) -> None: ...  # type: ignore[override]
    def __rmul__(self, arg: Any, *, recursive: bool = ...  # type: ignore[override]
        ) -> Qube: ...
    def __rsub__(self, arg: Any) -> None: ...  # type: ignore[override]
    def __setstate__(self, state: dict[str, Any]) -> None: ...
    def __sub__(self, arg: Any) -> None: ...  # type: ignore[override]
    @staticmethod
    def as_matrix3(arg: Any, *, recursive: bool = ...) -> Matrix3: ...
    @staticmethod
    def axis_rotation(angle: ScalarLike, axis: int = ..., *, recursive: bool = ...
        ) -> Matrix3: ...
    @staticmethod
    def from_euler(ai: ScalarLike, aj: ScalarLike, ak: ScalarLike,
        axes: str | tuple[int, int, int, int] = ...) -> Matrix3: ...
    def mean(self, axis: int | Sequence[int] | None = ..., *, recursive: bool = ...,  # type: ignore[override]
        builtins: bool | None = ..., dtype: Any | None = ..., out: Any | None = ...
        ) -> None: ...
    @staticmethod
    def pole_rotation(ra: ScalarLike, dec: ScalarLike) -> Matrix3: ...
    def reciprocal(self, *, recursive: bool = ..., nozeros: bool = ...  # type: ignore[override]
        ) -> Matrix3: ...
    def rotate(self, arg: QubeLike, *, recursive: bool = ...) -> Qube: ...
    def sum(self, axis: int | Sequence[int] | None = ..., *, recursive: bool = ...,  # type: ignore[override]
        builtins: bool | None = ..., out: Any | None = ...) -> None: ...
    def to_euler(self, axes: str | tuple[int, int, int, int] = ...
        ) -> tuple[Scalar, Scalar, Scalar]: ...
    def to_quaternion(self, recursive: bool = ...) -> Quaternion: ...
    @staticmethod
    def twovec(vector1: VectorLike, axis1: int, vector2: VectorLike, axis2: int, *,
        recursive: bool = ...) -> Matrix3: ...
    def unrotate(self, arg: QubeLike, *, recursive: bool = ...) -> Qube: ...
    @staticmethod
    def x_rotation(angle: ScalarLike, *, recursive: bool = ...) -> Matrix3: ...
    @staticmethod
    def y_rotation(angle: ScalarLike, *, recursive: bool = ...) -> Matrix3: ...
    @staticmethod
    def z_rotation(angle: ScalarLike, *, recursive: bool = ...) -> Matrix3: ...

##########################################################################################
