##########################################################################################
# polymath/qube.pyi
##########################################################################################
"""Type stub for :mod:`polymath.qube`.

The `src` tree carries no inline annotations, so type information for public symbols is
published here instead. These stubs describe the shape of the API exactly: every public
name, its parameters, which of them are keyword-only, and which have defaults. Types are
taken from the docstrings wherever those state one unambiguously, and are left as `Any`
where they do not, rather than guessed at.
"""

import builtins
from typing import Any, ClassVar, TypeAlias

import numpy as np
from numpy.typing import NDArray

from polymath.unit import Unit
from polymath.boolean import Boolean
from polymath.scalar import Scalar
from polymath.typedefs import BooleanLike, MaskType, QubeLike, ScalarLike, ValsType





__all__ = ['Qube']

# Anything the constructors accept in place of a value: a PolyMath object, a NumPy array,
# a nested sequence, or a single number.
_Arraylike: TypeAlias = (Qube | NDArray[Any] | np.ma.MaskedArray[Any, Any] |
                         list[Any] | tuple[Any, ...] | float | builtins.int | bool)

# A bare "tuple" in a docstring, which is usually but not always a shape
_ShapeOrTuple: TypeAlias = tuple[Any, ...]

class Qube:
    # Lets NumPy defer to these operators rather than its own
    __array_priority__: ClassVar[builtins.int]

    # Qube compares by value and is mutable, so it is not hashable
    __hash__: ClassVar[None]  # type: ignore[assignment]
    def __abs__(self, *, recursive: bool = ...) -> Qube: ...
    def __add__(self, arg: QubeLike, *, recursive: bool = ...) -> Qube: ...
    def __and__(self, arg: BooleanLike) -> Boolean: ...
    def __bool__(self) -> Boolean: ...
    def __copy__(self) -> Qube: ...
    def __eq__(self, arg: object) -> Boolean: ...  # type: ignore[override]
    def __float__(self) -> float: ...
    def __floordiv__(self, arg: QubeLike) -> Qube: ...
    def __ge__(self, arg: QubeLike) -> Boolean: ...
    def __getitem__(self, indx: Any) -> Qube: ...
    def __getstate__(self) -> dict: ...  # type: ignore[type-arg]
    def __gt__(self, arg: QubeLike) -> Boolean: ...
    def __iadd__(self, arg: QubeLike) -> Qube: ...  # type: ignore[misc]
    def __iand__(self, arg: BooleanLike) -> Qube: ...
    def __ifloordiv__(self, arg: QubeLike) -> Qube: ...
    def __imod__(self, arg: QubeLike) -> Qube: ...  # type: ignore[misc]
    def __imul__(self, arg: QubeLike) -> Qube: ...  # type: ignore[misc]
    def __init__(self, arg: QubeLike, mask: BooleanLike = ..., *,
        derivs: dict[str, Qube] = ..., unit: Unit | None = ..., nrank: int | None = ...,
        drank: int | None = ..., example: Qube | None = ...,
        default: QubeLike | None = ..., op: str = ...) -> None: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> Boolean: ...
    def __ior__(self, arg: BooleanLike) -> Qube: ...
    def __ipow__(self, arg: QubeLike) -> Qube: ...
    def __isub__(self, arg: QubeLike) -> Qube: ...  # type: ignore[misc]
    def __iter__(self) -> None: ...
    def __itruediv__(self, arg: QubeLike) -> Qube: ...  # type: ignore[misc]
    def __ixor__(self, arg: BooleanLike) -> Qube: ...
    def __le__(self, arg: QubeLike) -> Boolean: ...
    def __len__(self) -> int: ...
    def __lt__(self, arg: QubeLike) -> Boolean: ...
    def __matmul__(self, arg: Qube) -> Qube: ...
    def __mod__(self, arg: QubeLike, *, recursive: bool = ...) -> Qube: ...
    def __mul__(self, arg: QubeLike, *, recursive: bool = ...) -> Qube: ...
    def __ne__(self, arg: object) -> Boolean: ...  # type: ignore[override]
    def __neg__(self, *, recursive: bool = ...) -> Qube: ...
    @staticmethod
    def __new__(subtype: type, *values: Any, **keywords: Any) -> Qube: ...
    def __or__(self, arg: BooleanLike) -> Boolean: ...
    def __pos__(self, *, recursive: bool = ...) -> Qube: ...
    def __pow__(self, arg: QubeLike) -> Qube: ...
    def __radd__(self, arg: QubeLike, *, recursive: bool = ...) -> Qube: ...
    def __rand__(self, arg: BooleanLike) -> Boolean: ...
    def __repr__(self) -> str: ...
    def __rfloordiv__(self, arg: QubeLike) -> Qube: ...
    def __rmod__(self, arg: QubeLike, *, recursive: bool = ...) -> Qube: ...
    def __rmul__(self, arg: QubeLike, *, recursive: bool = ...) -> Qube: ...
    def __ror__(self, arg: BooleanLike) -> Boolean: ...
    def __rsub__(self, arg: QubeLike, *, recursive: bool = ...) -> Qube: ...
    def __rtruediv__(self, arg: QubeLike, *, recursive: bool = ...) -> Qube: ...
    def __rxor__(self, arg: BooleanLike) -> Boolean: ...
    def __setitem__(self, indx: Any, arg: QubeLike) -> None: ...
    def __setstate__(self, state: dict[str, Any]) -> None: ...
    def __str__(self) -> str: ...
    def __sub__(self, arg: QubeLike, *, recursive: bool = ...) -> Qube: ...
    def __truediv__(self, arg: QubeLike, *, recursive: bool = ...) -> Qube: ...
    def __xor__(self, arg: BooleanLike) -> Boolean: ...
    def abs(self) -> Qube: ...
    def add_attr(self, name: str, value: Any | None = ...) -> Qube: ...
    def all(self, axis: int | tuple[int, ...] | None = ..., *,
        builtins: bool | None = ..., masked: bool | None = ..., out: Any | None = ...
        ) -> Boolean | bool: ...
    def all_true_or_masked(self, axis: int | tuple[int, ...] | None = ..., *,
        builtins: bool | None = ...) -> Boolean | bool: ...
    @staticmethod
    def and_(*masks: BooleanLike) -> np.ndarray | bool: ...
    @property
    def antimask(self) -> MaskType: ...
    def any(self, axis: int | tuple[int, ...] | None = ..., *,
        builtins: bool | None = ..., masked: bool | None = ..., out: Any | None = ...
        ) -> Boolean | bool: ...
    def any_true_or_masked(self, axis: int | tuple[int, ...] | None = ..., *,
        builtins: bool | None = ...) -> Boolean | bool: ...
    def as_all_constant(self, constant: QubeLike | None = ..., *, recursive: bool = ...
        ) -> Qube: ...
    def as_all_masked(self, *, recursive: bool = ...) -> Qube: ...
    def as_bool(self, *, copy: bool = ..., builtins: bool = ...) -> Qube: ...
    def as_builtin(self, masked: float | int | bool | None = ...
        ) -> Qube | float | int | bool | None: ...
    @staticmethod
    def as_diagonal(arg: Qube, axis: int,
        classes: type | list[type] | tuple[type, ...] = ..., recursive: bool = ...
        ) -> Qube: ...
    def as_float(self, *, recursive: bool = ..., copy: bool = ..., builtins: bool = ...
        ) -> Qube: ...
    def as_int(self, *, copy: bool = ..., builtins: bool = ...) -> Qube | int: ...
    def as_mask_where_nonzero(self) -> np.ndarray | bool: ...
    def as_mask_where_nonzero_or_masked(self) -> np.ndarray | bool: ...
    def as_mask_where_zero(self) -> np.ndarray | bool: ...
    def as_mask_where_zero_or_masked(self) -> np.ndarray | bool: ...
    def as_numeric(self, *, recursive: bool = ...) -> Qube: ...
    @staticmethod
    def as_one_bool(value: Any) -> Any: ...
    def as_one_masked(self, *, recursive: bool = ...) -> Qube: ...
    def as_readonly(self, *, recursive: bool = ...) -> Qube: ...
    def as_size_zero(self, axis: int = ..., *, recursive: bool = ...) -> Qube: ...
    def as_this_type(self, arg: QubeLike, *, recursive: bool = ..., coerce: bool = ...,
        op: str = ...) -> Qube: ...
    def broadcast(*objects: QubeLike | None, recursive: bool = ...,
        _protected: bool = ...) -> tuple[Any, ...]: ...
    def broadcast_into_shape(self, shape: tuple[int, ...], *, recursive: bool = ...,
        _protected: bool = ...) -> Qube: ...
    def broadcast_to(self, shape: tuple[int, ...], *, recursive: bool = ...,
        _protected: bool = ...) -> Qube: ...
    def broadcasted_shape(*objects: QubeLike | None, item: list | tuple = ...  # type: ignore[type-arg]
        ) -> tuple[int, ...]: ...
    def cast(self, classes: type | list[type] | tuple[type, ...]) -> Qube: ...
    def chain(self, arg: Qube) -> Qube: ...
    def clip(self, lower: Any, upper: Any, *, remask: bool = ..., inclusive: bool = ...
        ) -> Qube: ...
    def clone(self, *, recursive: bool = ...,
        preserve: list[str] | tuple[str, ...] | set[str] = ..., retain_cache: bool = ...
        ) -> Qube: ...
    def collapse_mask(self, *, recursive: bool = ...) -> Qube: ...
    def confirm_unit(self, unit: Unit | None) -> Qube: ...
    def copy(self, *, recursive: bool = ..., readonly: bool = ...) -> Qube: ...
    @property
    def corners(self) -> tuple[tuple[int, int], tuple[int, int]] | None: ...
    def count_masked(self) -> int: ...
    def count_unmasked(self) -> int: ...
    @staticmethod
    def cross(arg1: Qube, arg2: Qube, axis1: int = ..., axis2: int = ..., *,
        classes: type | list[type] | tuple[type, ...] = ..., recursive: bool = ...
        ) -> Qube: ...
    @property
    def default(self) -> np.ndarray | float | int | bool: ...
    def delete_deriv(self, key: str, *, override: bool = ...) -> None: ...
    def delete_derivs(self, *, override: bool = ...,
        preserve: list[str] | tuple[str, ...] | set[str] | None = ...) -> None: ...
    @property
    def denom(self) -> tuple[int, ...]: ...
    @property
    def derivs(self) -> dict[str, Qube]: ...
    @staticmethod
    def dot(arg1: Qube, arg2: Qube, axis1: int = ..., axis2: int = ..., *,
        classes: type | list[type] | tuple[type, ...] = ..., recursive: bool = ...
        ) -> Qube: ...
    @property
    def drank(self) -> int: ...
    @property
    def dsize(self) -> int: ...
    def dtype(self) -> str: ...
    def expand_mask(self, *, recursive: bool = ...) -> Qube: ...
    def extract_denom(self, axis: int, index: int,
        classes: type | list[type] | tuple[type, ...] = ...) -> Qube: ...
    def extract_denoms(self) -> list: ...  # type: ignore[type-arg]
    def extract_numer(self, axis: int, index: int,
        classes: type | list[type] | tuple[type, ...] = ..., *, recursive: bool = ...
        ) -> Qube: ...
    @classmethod
    def filled(cls, shape: tuple[int, ...], fill: QubeLike = ..., *,
        numer: tuple[int, ...] | None = ..., denom: tuple[int, ...] = ...,
        mask: BooleanLike = ...) -> Qube: ...
    def flatten(self, *, recursive: bool = ...) -> Qube: ...
    def flatten_denom(self) -> Qube: ...
    def flatten_numer(self, classes: type | list[type] | tuple[type, ...] = ..., *,
        recursive: bool = ...) -> Qube: ...
    @classmethod
    def from_scalars(cls, *scalars: QubeLike, recursive: bool = ...,
        readonly: bool = ..., classes: type | list[type] | tuple[type, ...] = ...
        ) -> Qube: ...
    def identity(self) -> None: ...
    def insert_deriv(self, key: str, deriv: Qube, *, override: bool = ...) -> Qube: ...
    def insert_derivs(self, derivs: dict[str, Qube], *, override: bool = ...) -> Qube: ...
    def into_unit(self, *, recursive: bool = ...
        ) -> np.ndarray | float | int | bool | tuple: ...  # type: ignore[type-arg]
    @staticmethod
    def is_above(arg: Any, high: Any, *, inclusive: bool = ...) -> bool: ...
    def is_all_masked(self) -> bool: ...
    @staticmethod
    def is_below(arg: Any, high: Any, *, inclusive: bool = ...) -> bool: ...
    def is_bool(self) -> bool: ...
    def is_float(self) -> bool: ...
    @staticmethod
    def is_inside(arg: Any, low: Any, high: Any, *, inclusive: bool = ...) -> bool: ...
    def is_int(self) -> bool: ...
    def is_numeric(self) -> bool: ...
    @staticmethod
    def is_one_false(value: Any) -> bool: ...
    @staticmethod
    def is_one_true(value: Any) -> bool: ...
    @staticmethod
    def is_outside(arg: Any, low: Any, high: Any, *, inclusive: bool = ...) -> bool: ...
    def is_unitless(self) -> bool: ...
    @property
    def isize(self) -> int: ...
    @property
    def item(self) -> tuple[int, ...]: ...
    def join_items(self, classes: type | list[type] | tuple[type, ...]) -> Qube: ...
    def len(self) -> int: ...
    def logical_not(self) -> Boolean: ...
    @property
    def mask(self) -> MaskType: ...
    def mask_where(self, mask: BooleanLike, replace: Any | None = ..., *,
        remask: bool = ..., recursive: bool = ...) -> Qube: ...
    def mask_where_between(self, lower: QubeLike, upper: QubeLike, *,
        mask_endpoints: bool | tuple[bool, ...] = ..., replace: QubeLike | None = ...,
        remask: bool = ...) -> Qube: ...
    def mask_where_eq(self, match: Any, replace: Any | None = ..., *, remask: bool = ...
        ) -> Qube: ...
    def mask_where_ge(self, limit: Any, replace: Any | None = ..., *, remask: bool = ...
        ) -> Qube: ...
    def mask_where_gt(self, limit: Any, replace: Any | None = ..., *, remask: bool = ...
        ) -> Qube: ...
    def mask_where_le(self, limit: Any, replace: Any | None = ..., *, remask: bool = ...
        ) -> Qube: ...
    def mask_where_lt(self, limit: Any, replace: Any | None = ..., *, remask: bool = ...
        ) -> Qube: ...
    def mask_where_ne(self, match: Any, replace: Any | None = ..., *, remask: bool = ...
        ) -> Qube: ...
    def mask_where_outside(self, lower: QubeLike, upper: QubeLike, *,
        mask_endpoints: bool | tuple[bool, ...] = ..., replace: QubeLike | None = ...,
        remask: bool = ...) -> Qube: ...
    def masked_single(self, *, recursive: bool = ...) -> Qube: ...
    def match_readonly(self, arg: Qube) -> Qube: ...
    def mean(self, axis: int | tuple[int, ...] | None = ..., *, recursive: bool = ...,
        builtins: bool | None = ..., masked: bool | None = ..., dtype: Any | None = ...,
        out: Any | None = ...) -> Qube | float | int: ...
    def move_axis(self, source: int | tuple[int, ...],
        destination: int | tuple[int, ...], *, recursive: bool = ...,
        rank: int | None = ...) -> Qube: ...
    @property
    def mvals(self) -> np.ma.MaskedArray: ...
    def ndenumerate(self) -> None: ...
    @property
    def ndim(self) -> int: ...
    @property
    def ndims(self) -> int: ...
    @staticmethod
    def norm(arg: Qube, axis: int = ..., *,
        classes: type | list[type] | tuple[type, ...] = ..., recursive: bool = ...
        ) -> Qube: ...
    @staticmethod
    def norm_sq(arg: QubeLike, axis: int = ..., *,
        classes: type | list[type] | tuple[type, ...] = ..., recursive: bool = ...
        ) -> Qube: ...
    @property
    def nrank(self) -> int: ...
    @property
    def nsize(self) -> int: ...
    @property
    def numer(self) -> tuple[int, ...]: ...
    @classmethod
    def ones(cls, shape: tuple[int, ...], dtype: str = ..., *,
        numer: tuple[int, ...] | None = ..., denom: tuple[int, ...] = ...,
        mask: BooleanLike = ...) -> Qube: ...
    @staticmethod
    def or_(*masks: BooleanLike) -> np.ndarray | bool: ...
    @staticmethod
    def outer(arg1: Qube, arg2: Qube,
        classes: type | list[type] | tuple[type, ...] = ..., recursive: bool = ...
        ) -> Qube: ...
    def pickle_digits(self) -> str | float | int: ...
    def pickle_reference(self) -> str | float | int: ...
    @staticmethod
    def prefer_builtins(status: bool | None = ...) -> bool: ...
    @property
    def rank(self) -> int: ...
    @property
    def readonly(self) -> bool: ...
    def reciprocal(self, *, recursive: bool = ..., nozeros: bool = ...) -> None: ...
    def remask(self, mask: BooleanLike, *, recursive: bool = ..., check: bool = ...
        ) -> Qube: ...
    def remask_or(self, mask: BooleanLike, *, recursive: bool = ..., check: bool = ...
        ) -> Qube: ...
    def rename_deriv(self, key: str, new_key: str, *, method: str = ...) -> Qube: ...
    def require_writable(self, force: bool = ...) -> Qube: ...
    def require_writeable(self, force: bool = ...) -> Qube: ...
    def reshape(self, shape: tuple[int, ...] | int, *, recursive: bool = ...) -> Qube: ...
    def reshape_denom(self, shape: tuple[int, ...]) -> Qube: ...
    def reshape_numer(self, shape: tuple[int, ...],
        classes: type | list[type] | tuple[type, ...] = ..., recursive: bool = ...
        ) -> Qube: ...
    def rms(self) -> Scalar: ...
    def roll_axis(self, axis: int, start: int = ..., *, recursive: bool = ...,
        rank: int | None = ...) -> Qube: ...
    @staticmethod
    def set_default_pickle_digits(digits: int | float | str | tuple = ...,  # type: ignore[type-arg]
        reference: int | float | str | tuple = ...) -> None: ...  # type: ignore[type-arg]
    def set_pickle_digits(self, digits: int | float | str | tuple = ...,  # type: ignore[type-arg]
        reference: int | float | str | tuple = ...) -> None: ...  # type: ignore[type-arg]
    def set_unit(self, unit: Unit | None, *, override: bool = ...) -> None: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    def shrink(self, antimask: BooleanLike) -> Qube: ...
    @property
    def size(self) -> int: ...
    def slice_numer(self, axis: int, index1: int, index2: int,
        classes: type | list[type] | tuple[type, ...] = ..., *, recursive: bool = ...
        ) -> Qube: ...
    def split_items(self, nrank: int, classes: type | list[type] | tuple[type, ...]
        ) -> Qube: ...
    @staticmethod
    def stack(*args: ScalarLike | None, recursive: bool = ...) -> Qube: ...
    def sum(self, axis: int | tuple[int, ...] | None = ..., *, recursive: bool = ...,
        builtins: bool | None = ..., masked: bool | None = ..., out: Any | None = ...
        ) -> Qube | float | int: ...
    def swap_axes(self, axis1: int, axis2: int, *, recursive: bool = ...) -> Qube: ...
    def swap_items(self, classes: type | list[type] | tuple[type, ...]) -> Qube: ...
    def transpose_denom(self, axis1: int = ..., axis2: int = ...) -> Qube: ...
    def transpose_numer(self, axis1: int = ..., axis2: int = ..., *,
        recursive: bool = ...) -> Qube: ...
    def tvl_all(self, axis: int | tuple[int, ...] | None = ...,
        builtins: bool | None = ..., masked: bool | None = ...) -> Boolean | bool: ...
    def tvl_and(self, arg: BooleanLike, builtins: bool | None = ...,
        masked: bool | None = ...) -> Boolean | bool: ...
    def tvl_any(self, axis: int | tuple[int, ...] | None = ...,
        builtins: bool | None = ..., masked: bool | None = ...) -> Boolean | bool: ...
    def tvl_eq(self, arg: BooleanLike, builtins: bool | None = ...) -> Boolean | bool: ...
    def tvl_ge(self, arg: QubeLike, builtins: bool | None = ...) -> Boolean | bool: ...
    def tvl_gt(self, arg: QubeLike, builtins: bool | None = ...) -> Boolean | bool: ...
    def tvl_le(self, arg: QubeLike, builtins: bool | None = ...) -> Boolean | bool: ...
    def tvl_lt(self, arg: QubeLike, builtins: bool | None = ...) -> Boolean | bool: ...
    def tvl_ne(self, arg: BooleanLike, builtins: bool | None = ...) -> Boolean | bool: ...
    def tvl_or(self, arg: BooleanLike, builtins: bool | None = ...,
        masked: bool | None = ...) -> Boolean | bool: ...
    def unique_deriv_name(self, key: str, *objects: Qube) -> str: ...
    @property
    def unit_(self) -> Unit | None: ...
    @property
    def units(self) -> Unit | None: ...
    def unshrink(self, antimask: BooleanLike, shape: tuple[int, ...] = ...) -> Qube: ...
    @property
    def vals(self) -> ValsType: ...
    @property
    def values(self) -> ValsType: ...
    def with_deriv(self, key: str, value: Qube, *, method: str = ...) -> Qube: ...
    def without_deriv(self, key: str) -> Qube: ...
    def without_derivs(self, *,
        preserve: list[str] | tuple[str, ...] | set[str] | None = ...) -> Qube: ...
    def without_mask(self, *, recursive: bool = ...) -> Qube: ...
    def without_unit(self, *, recursive: bool = ...) -> Qube: ...
    @property
    def wod(self) -> Qube: ...
    def zero(self) -> Qube: ...
    @classmethod
    def zeros(cls, shape: tuple[int, ...], dtype: str = ..., *,
        numer: tuple[int, ...] | None = ..., denom: tuple[int, ...] = ...,
        mask: BooleanLike = ...) -> Qube: ...

##########################################################################################
