##########################################################################################
# polymath/scalar.pyi
##########################################################################################
"""Type stub for :mod:`polymath.scalar`.

The `src` tree carries no inline annotations, so type information for public symbols is
published here instead. These stubs describe the shape of the API exactly: every public
name, its parameters, which of them are keyword-only, and which have defaults. Types are
taken from the docstrings wherever those state one unambiguously, and are left as `Any`
where they do not, rather than guessed at.
"""

import builtins
from typing import Any


from polymath.qube import Qube
import numpy as np
from polymath.boolean import Boolean
from polymath.typedefs import ScalarLike


__all__ = ['Scalar']

class Scalar(Qube):
    HALFPI: Scalar
    INF: Scalar
    MASKED: Scalar
    NEGINF: Scalar
    ONE: Scalar
    PI: Scalar
    THREE: Scalar
    TWO: Scalar
    TWOPI: Scalar
    ZERO: Scalar
    def __abs__(self, *, recursive: bool = ...) -> Scalar: ...  # type: ignore[override]
    def __ge__(self, arg: Any, *, builtins: bool = ...  # type: ignore[override]
        ) -> Boolean | bool: ...
    def __gt__(self, arg: Any, *, builtins: bool = ...  # type: ignore[override]
        ) -> Boolean | bool: ...
    def __le__(self, arg: Any, *, builtins: bool = ...  # type: ignore[override]
        ) -> Boolean | bool: ...
    def __lt__(self, arg: Any, *, builtins: bool = ...  # type: ignore[override]
        ) -> Boolean | bool: ...
    def __pow__(self, expo: ScalarLike, *, recursive: bool = ...) -> Scalar: ...
    def __round__(self, digits: builtins.int) -> Scalar: ...
    def abs(self, *, recursive: bool = ...) -> Scalar: ...
    def arccos(self, *, recursive: bool = ..., check: bool = ...) -> Scalar: ...
    def arcsin(self, *, recursive: bool = ..., check: bool = ...) -> Scalar: ...
    def arctan(self, *, recursive: bool = ...) -> Scalar: ...
    def arctan2(self, arg: ScalarLike, *, recursive: bool = ...) -> Scalar: ...
    def argmax(self, axis: builtins.int | tuple[builtins.int, ...] | None = ..., *,
        builtins: bool | None = ...,
        masked: builtins.int | None = ...) -> Scalar | builtins.int: ...
    def argmin(self, axis: builtins.int | tuple[builtins.int, ...] | None = ..., *,
        builtins: bool | None = ...,
        masked: builtins.int | None = ...) -> Scalar | builtins.int: ...
    def as_index(self, *, masked: builtins.int | None = ...
        ) -> np.ndarray | builtins.int: ...
    def as_index_and_mask(self, *, purge: bool = ..., masked: builtins.int | None = ...
        ) -> None: ...
    @staticmethod
    def as_scalar(arg: Any, *, recursive: bool = ...) -> Scalar: ...
    def cos(self, *, recursive: bool = ...) -> Scalar: ...
    def eval_quadratic(self, a: ScalarLike, b: ScalarLike, c: ScalarLike, *,
        recursive: bool = ...) -> Scalar: ...
    def exp(self, *, recursive: bool = ..., check: bool = ...) -> Scalar: ...
    def frac(self, *, recursive: bool = ...) -> Scalar: ...
    def identity(self) -> Scalar: ...  # type: ignore[override]
    def int(self, top: builtins.int | None = ..., *, remask: bool = ..., clip: bool = ...,
        inclusive: bool = ..., shift: bool | None = ..., builtins: bool | None = ...,
        masked: builtins.int | None = ...) -> Scalar | builtins.int: ...
    def log(self, *, recursive: bool = ..., check: bool = ...) -> Scalar: ...
    def max(self, axis: builtins.int | tuple[builtins.int, ...] | None = ..., *,
        builtins: bool | None = ..., masked: float | builtins.int | None = ...,
        out: Any | None = ...) -> Scalar | float | builtins.int: ...
    @staticmethod
    def maximum(*args: ScalarLike) -> Scalar: ...
    def median(self, axis: builtins.int | tuple[builtins.int, ...] | None = ..., *,
        builtins: bool | None = ..., masked: float | builtins.int | None = ...,
        out: Any | None = ...) -> Scalar | float | builtins.int: ...
    def min(self, axis: builtins.int | tuple[builtins.int, ...] | None = ..., *,
        builtins: bool | None = ..., masked: float | builtins.int | None = ...,
        out: Any | None = ...) -> Scalar | float | builtins.int: ...
    @staticmethod
    def minimum(*args: ScalarLike) -> Scalar: ...
    def reciprocal(self, *, recursive: bool = ..., nozeros: bool = ...  # type: ignore[override]
        ) -> Scalar: ...
    def sign(self, *, zeros: bool = ..., builtins: bool | None = ...,
        masked: builtins.int | None = ...) -> Scalar | builtins.int: ...
    def sin(self, *, recursive: bool = ...) -> Scalar: ...
    @staticmethod
    def solve_quadratic(a: ScalarLike, b: ScalarLike, c: ScalarLike, *,
        recursive: bool = ..., include_antimask: bool = ...
        ) -> tuple[Scalar, Scalar] | tuple[Scalar, Scalar, Boolean]: ...
    def sort(self, axis: builtins.int = ...) -> Scalar: ...
    def sqrt(self, *, recursive: bool = ..., check: bool = ...) -> Scalar: ...
    def tan(self, *, recursive: bool = ...) -> Scalar: ...
    def to_scalar(self, indx: builtins.int, *, recursive: bool = ...) -> Scalar: ...

##########################################################################################
