##########################################################################################
# polymath/scalar.pyi
##########################################################################################
"""Type stub for :mod:`polymath.scalar`.

The `src` tree carries no inline annotations, so type information for public symbols is
published here instead. These stubs describe the shape of the API exactly: every public
name, its parameters, which of them are keyword-only, and which have defaults. Types are
taken from the docstrings wherever those state one unambiguously, and are left as `Any`
where they do not, rather than guessed at.
"""

import builtins
from typing import Any

from numpy.typing import NDArray

from polymath.qube import Qube, _Arraylike, _ShapeOrTuple

class Scalar(Qube):
    HALFPI: Scalar
    INF: Scalar
    MASKED: Scalar
    NEGINF: Scalar
    ONE: Scalar
    PI: Scalar
    THREE: Scalar
    TWO: Scalar
    TWOPI: Scalar
    ZERO: Scalar
    def __abs__(self, *, recursive: bool = ...) -> _Arraylike: ...  # type: ignore[override]
    def __ge__(self, arg: Any, *,
        builtins: bool = ...) -> _Arraylike | bool: ...
    def __gt__(self, arg: Any, *,
        builtins: bool = ...) -> _Arraylike | bool: ...
    def __le__(self, arg: Any, *,
        builtins: bool = ...) -> _Arraylike | bool: ...
    def __lt__(self, arg: Any, *,
        builtins: bool = ...) -> _Arraylike | bool: ...
    def __pow__(self, expo: Any, *, recursive: Any = ...) -> Any: ...
    def __round__(self, digits: builtins.int) -> _Arraylike: ...
    def abs(self, *, recursive: bool = ...) -> _Arraylike: ...
    def arccos(self, *, recursive: bool = ..., check: bool = ...) -> _Arraylike: ...
    def arcsin(self, *, recursive: bool = ..., check: bool = ...) -> _Arraylike: ...
    def arctan(self, *, recursive: bool = ...) -> _Arraylike: ...
    def arctan2(self, arg: Any, *, recursive: bool = ...) -> _Arraylike: ...
    def argmax(self, axis: builtins.int | None = ..., *, builtins: bool | None = ...,
        masked: Any = ...) -> _Arraylike | builtins.int: ...
    def argmin(self, axis: builtins.int | None = ..., *, builtins: bool | None = ...,
        masked: Any = ...) -> _Arraylike | builtins.int: ...
    def as_index(self, *, masked: Any = ...) -> NDArray[Any]: ...
    def as_index_and_mask(self, *, purge: bool = ...,
        masked: Any = ...) -> _ShapeOrTuple: ...
    @staticmethod
    def as_scalar(arg: Any, *, recursive: bool = ...) -> _Arraylike: ...
    def cos(self, *, recursive: bool = ...) -> _Arraylike: ...
    def eval_quadratic(self, a: Any, b: Any, c: Any, *,
        recursive: bool = ...) -> _Arraylike: ...
    def exp(self, *, recursive: bool = ..., check: bool = ...) -> _Arraylike: ...
    def frac(self, *, recursive: bool = ...) -> _Arraylike: ...
    def identity(self) -> _Arraylike: ...
    def int(self, top: builtins.int | None = ..., *, remask: bool = ...,
        clip: bool = ..., inclusive: bool = ..., shift: bool | None = ...,
        builtins: bool | None = ..., masked: Any = ...) -> _Arraylike | builtins.int: ...
    def log(self, *, recursive: bool = ..., check: bool = ...) -> _Arraylike: ...
    def max(self, axis: Any = ..., *, builtins: bool | None = ..., masked: Any = ...,
        out: Any = ...) -> _Arraylike | float | builtins.int: ...
    @staticmethod
    def maximum(*args: Any) -> Any: ...
    def median(self, axis: Any = ..., *, builtins: bool | None = ..., masked: Any = ...,
        out: Any = ...) -> _Arraylike | float | builtins.int: ...
    def min(self, axis: Any = ..., *, builtins: bool | None = ..., masked: Any = ...,
        out: Any = ...) -> _Arraylike | float | builtins.int: ...
    @staticmethod
    def minimum(*args: Any) -> Any: ...
    def reciprocal(self, *, recursive: bool = ..., nozeros: bool = ...) -> _Arraylike: ...
    def sign(self, *, zeros: bool = ..., builtins: bool | None = ...,
        masked: Any = ...) -> _Arraylike | builtins.int: ...
    def sin(self, *, recursive: bool = ...) -> _Arraylike: ...
    @staticmethod
    def solve_quadratic(a: Any, b: Any, c: Any, *, recursive: bool = ...,
        include_antimask: bool = ...) -> _ShapeOrTuple: ...
    def sort(self, axis: builtins.int = ...) -> _Arraylike: ...
    def sqrt(self, *, recursive: bool = ..., check: bool = ...) -> _Arraylike: ...
    def tan(self, *, recursive: bool = ...) -> _Arraylike: ...
    def to_scalar(self, indx: builtins.int, *, recursive: bool = ...) -> _Arraylike: ...

##########################################################################################
