##########################################################################################
# polymath/vector.pyi
##########################################################################################
"""Type stub for :mod:`polymath.vector`.

The `src` tree carries no inline annotations, so type information for public symbols is
published here instead. These stubs describe the shape of the API exactly: every public
name, its parameters, which of them are keyword-only, and which have defaults. Types are
taken from the docstrings wherever those state one unambiguously, and are left as `Any`
where they do not, rather than guessed at.
"""

import builtins
from typing import Any

from polymath.qube import Qube
from polymath.matrix import Matrix
from polymath.pair import Pair
from polymath.scalar import Scalar
from polymath.typedefs import ScalarLike, VectorLike
import numpy as np





__all__ = ['Vector']

class Vector(Qube):
    MASKED2: Vector
    MASKED3: Vector
    XAXIS2: Vector
    XAXIS3: Vector
    YAXIS2: Vector
    YAXIS3: Vector
    ZAXIS3: Vector
    ZERO2: Vector
    ZERO3: Vector
    def __abs__(self, recursive: bool = ...) -> Scalar: ...  # type: ignore[override]
    def __init__(self, arg: VectorLike, *args: Any, **kwargs: Any) -> None: ...
    def as_column(self, recursive: bool = ...) -> Matrix: ...
    def as_diagonal(self, *, recursive: bool = ...  # type: ignore[override]
        ) -> Matrix: ...
    def as_index(self, *, masked: ScalarLike | None = ...
        ) -> tuple[np.ndarray, ...]: ...
    def as_index_and_mask(self, *, purge: bool = ..., masked: ScalarLike | None = ...
        ) -> tuple: ...  # type: ignore[type-arg]
    def as_row(self, *, recursive: bool = ...) -> Matrix: ...
    @staticmethod
    def as_vector(arg: Any, *, recursive: bool = ...) -> Vector: ...
    def clip_component(self, axis: builtins.int, lower: ScalarLike, upper: ScalarLike,
        remask: bool = ...) -> Vector: ...
    @classmethod
    def combos(cls, *args: ScalarLike) -> Vector: ...
    def cross(self, arg: VectorLike, *, recursive: bool = ...  # type: ignore[override]
        ) -> Vector: ...
    def cross_product_as_matrix(self, *, recursive: bool = ...) -> Matrix: ...
    def dot(self, arg: VectorLike, *, recursive: bool = ...  # type: ignore[override]
        ) -> Scalar: ...
    def element_div(self, arg: VectorLike, recursive: bool = ...) -> Vector: ...
    def element_mul(self, arg: VectorLike, *, recursive: bool = ...) -> Vector: ...
    @staticmethod
    def from_scalars(*args: ScalarLike | None, recursive: bool = ...,  # type: ignore[override]
        readonly: bool = ...) -> Vector: ...
    def identity(self) -> None: ...
    def int(self, top: builtins.int | tuple[builtins.int, ...] | None = ..., *,
        remask: bool = ...,
        clip: bool | tuple[bool, ...] = ..., inclusive: bool | tuple[bool, ...] = ...,
        shift: bool | tuple[bool, ...] | None = ...) -> Vector: ...
    def mask_where_component_ge(self, axis: builtins.int, limit: ScalarLike,
        replace: ScalarLike | None = ..., remask: bool = ...) -> Vector: ...
    def mask_where_component_gt(self, axis: builtins.int, limit: ScalarLike,
        replace: ScalarLike | None = ..., remask: bool = ...) -> Vector: ...
    def mask_where_component_le(self, axis: builtins.int, limit: ScalarLike,
        replace: ScalarLike | None = ..., remask: bool = ...) -> Vector: ...
    def mask_where_component_lt(self, axis: builtins.int, limit: ScalarLike,
        replace: ScalarLike | None = ..., remask: bool = ...) -> Vector: ...
    def norm(self, *, recursive: bool = ...) -> Scalar: ...  # type: ignore[override]
    def norm_sq(self, *, recursive: bool = ...) -> Scalar: ...  # type: ignore[override]
    def outer(self, arg: VectorLike, *, recursive: bool = ...  # type: ignore[override]
        ) -> Matrix: ...
    def perp(self, arg: VectorLike, *, recursive: bool = ...) -> Vector: ...
    def proj(self, arg: VectorLike, *, recursive: bool = ...) -> Vector: ...
    def reciprocal(self, nozeros: bool = ...) -> Vector: ...  # type: ignore[override]
    def sep(self, arg: VectorLike, *, recursive: bool = ...) -> Scalar: ...
    def to_pair(self, axes: tuple[builtins.int, ...] = ..., *, recursive: bool = ...
        ) -> Pair: ...
    def to_scalar(self, indx: builtins.int, *, recursive: bool = ...) -> Scalar: ...
    def to_scalars(self, *, recursive: bool = ...) -> tuple: ...  # type: ignore[type-arg]
    def ucross(self, arg: VectorLike, *, recursive: bool = ...) -> Vector: ...
    def unit(self, *, recursive: bool = ...) -> Vector: ...
    def vector_scale(self, factor: Vector, recursive: bool = ...) -> Vector: ...
    def vector_unscale(self, factor: Vector, recursive: bool = ...) -> Vector: ...
    def with_norm(self, norm: ScalarLike = ..., *, recursive: bool = ...) -> Vector: ...

##########################################################################################
