##########################################################################################
# polymath/vector.pyi
##########################################################################################
"""Type stub for :mod:`polymath.vector`.

The `src` tree carries no inline annotations, so type information for public symbols is
published here instead. These stubs describe the shape of the API exactly: every public
name, its parameters, which of them are keyword-only, and which have defaults. Types are
taken from the docstrings wherever those state one unambiguously, and are left as `Any`
where they do not, rather than guessed at.
"""

import builtins
from typing import Any

from polymath.qube import Qube, _Arraylike, _ShapeOrTuple

__all__ = ['Vector']

class Vector(Qube):
    MASKED2: Vector
    MASKED3: Vector
    XAXIS2: Vector
    XAXIS3: Vector
    YAXIS2: Vector
    YAXIS3: Vector
    ZAXIS3: Vector
    ZERO2: Vector
    ZERO3: Vector
    def __abs__(self, recursive: bool = ...) -> _Arraylike: ...  # type: ignore[override]
    def __init__(self, arg: Any, *args: Any, **kwargs: Any) -> None: ...
    def as_column(self, recursive: bool = ...) -> _Arraylike: ...
    def as_diagonal(self, *, recursive: bool = ...) -> _Arraylike: ...  # type: ignore[override]
    def as_index(self, *, masked: Any = ...) -> _ShapeOrTuple: ...
    def as_index_and_mask(self, *, purge: bool = ...,
        masked: Any = ...) -> _ShapeOrTuple: ...
    def as_row(self, *, recursive: bool = ...) -> _Arraylike: ...
    @staticmethod
    def as_vector(arg: Any, *, recursive: bool = ...) -> _Arraylike: ...
    def clip_component(self, axis: builtins.int, lower: Any, upper: Any,
        remask: bool = ...) -> _Arraylike: ...
    @classmethod
    def combos(cls, *args: Any) -> _Arraylike: ...
    def cross(self, arg: Any, *, recursive: bool = ...) -> _Arraylike: ...  # type: ignore[override]
    def cross_product_as_matrix(self, *, recursive: bool = ...) -> _Arraylike: ...
    def dot(self, arg: Any, *, recursive: bool = ...) -> _Arraylike: ...  # type: ignore[override]
    def element_div(self, arg: Any, recursive: bool = ...) -> _Arraylike: ...
    def element_mul(self, arg: Any, *, recursive: bool = ...) -> _Arraylike: ...
    @staticmethod
    def from_scalars(*args: Any, recursive: bool = ...,  # type: ignore[override]
        readonly: bool = ...) -> _Arraylike: ...
    def identity(self) -> Any: ...
    def int(self, top: Any = ..., *, remask: bool = ..., clip: Any = ...,
        inclusive: Any = ..., shift: Any = ...) -> _Arraylike: ...
    def mask_where_component_ge(self, axis: builtins.int, limit: Any, replace: Any = ...,
        remask: bool = ...) -> _Arraylike: ...
    def mask_where_component_gt(self, axis: builtins.int, limit: Any, replace: Any = ...,
        remask: bool = ...) -> _Arraylike: ...
    def mask_where_component_le(self, axis: builtins.int, limit: Any, replace: Any = ...,
        remask: bool = ...) -> _Arraylike: ...
    def mask_where_component_lt(self, axis: builtins.int, limit: Any, replace: Any = ...,
        remask: bool = ...) -> _Arraylike: ...
    def norm(self, *, recursive: bool = ...) -> _Arraylike: ...  # type: ignore[override]
    def norm_sq(self, *, recursive: bool = ...) -> _Arraylike: ...  # type: ignore[override]
    def outer(self, arg: Any, *, recursive: bool = ...) -> _Arraylike: ...  # type: ignore[override]
    def perp(self, arg: Any, *, recursive: bool = ...) -> _Arraylike: ...
    def proj(self, arg: Any, *, recursive: bool = ...) -> _Arraylike: ...
    def reciprocal(self, nozeros: bool = ...) -> Any: ...  # type: ignore[override]
    def sep(self, arg: Any, *, recursive: bool = ...) -> _Arraylike: ...
    def to_pair(self, axes: _ShapeOrTuple = ..., *,
        recursive: bool = ...) -> _Arraylike: ...
    def to_scalar(self, indx: builtins.int, *, recursive: bool = ...) -> _Arraylike: ...
    def to_scalars(self, *, recursive: bool = ...) -> _ShapeOrTuple: ...
    def ucross(self, arg: Any, *, recursive: bool = ...) -> _Arraylike: ...
    def unit(self, *, recursive: bool = ...) -> _Arraylike: ...
    def vector_scale(self, factor: _Arraylike, recursive: bool = ...) -> _Arraylike: ...
    def vector_unscale(self, factor: _Arraylike, recursive: bool = ...) -> _Arraylike: ...
    def with_norm(self, norm: Any = ..., *, recursive: bool = ...) -> _Arraylike: ...

##########################################################################################
